Adding gif and tape scilla
edoardottt/images pull request #10
Opened 2023-10-15 02:21 UTC by PaolaDaft

Hey, issue #5 is done c;

2023-10-15 06:28 UTC, edoardottt requested changes

2023-10-15 06:28 UTC, edoardottt commented on scilla/scilla.tape
> +Set FontSize 32
imo the font size is too high... what if we try with something like 17 ? let's see how it goes

2023-10-15 06:28 UTC, edoardottt commented on scilla/scilla.tape
> +Sleep 5s
Maybe we should sleep a lil bit longer here, like 8s

2023-10-15 06:31 UTC, edoardottt requested changes

2023-10-15 06:31 UTC, edoardottt commented on scilla/scilla.tape
> +Type "scilla subdomain -target google.com" Sleep 500ms  Enter
sleep a lil bit longer, like 1500ms

2023-10-16 17:58 UTC, PaolaDaft commented
I already made the changes you requested, I also modified the size, let me know if you want another change 👀

2023-10-16 18:52 UTC, edoardottt requested changes
Requesting small changes

2023-10-16 18:52 UTC, edoardottt commented on scilla/scilla.tape
> +Set FontSize 17
Let's try with `16`

2023-10-16 18:52 UTC, edoardottt commented on scilla/scilla.tape
> +Set Width 1920
Width `1200` is okay

2023-10-16 18:52 UTC, edoardottt commented on scilla/scilla.tape
> +Set Height 944
Height `600` is okay

2023-10-16 18:52 UTC, edoardottt commented on scilla/scilla.tape
> +Sleep 8s
Sleep for a bit longer, like `10s`

2023-10-16 19:30 UTC, PaolaDaft commented
Done, something else? 👀

2023-10-17 05:38 UTC, edoardottt approved these changes
lgtm

2023-10-17 05:39 UTC, edoardottt commented
Do you know why at a certain point the enumeration stops? :/

2023-10-17 17:29 UTC, PaolaDaft commented
From what I see, it's because the whole numbering takes about 4 minutes, and neither this gif nor the one you had before completes the numbering ;-;

2023-10-17 18:16 UTC, PaolaDaft commented
Oh, and it also has to do with the network, if the numbering is slower or faster. I tried with a 40s sleep and the numbering reaches 6%, on my machine

2023-10-18 07:19 UTC, edoardottt commented
I don't mean to complete the enumeration, 100% would be too much to show. But at least some seconds going forward without stopping itself. Have you tried to produce the gif multiple times? Does it always stop?

2023-10-18 19:02 UTC, PaolaDaft commented
Yes, if I have tried to produce the gif several times, in most of them it stops, the one that has not stopped so much is this one:
![scilla4](https://github.com/edoardottt/images/assets/68626833/9baad84e-fb1e-48e2-a27b-4f9e563618aa)

2023-10-23 07:16 UTC, edoardottt approved these changes
lgtm

2023-10-23 07:16 UTC, merged