Adding cariddi gif and doc .tape
edoardottt/images pull request #11
Opened 2023-10-15 03:15 UTC by PaolaDaft

Issue #4 is done :)

2023-10-15 06:31 UTC, edoardottt requested changes
I've added some changes to do...

anyway... the output is not the same as before. I tried on my machine and if I use
```console
echo http://testphp.vulnweb.com/ | cariddi
```

I get the same result as the old gif... maybe you tried many times and you are limited?

2023-10-15 06:31 UTC, edoardottt commented on cariddi/cariddi.tape
> +Set FontSize 32
same as scilla let's reduce the font size

2023-10-15 06:31 UTC, edoardottt commented on cariddi/cariddi.tape
> +Sleep 5s
same here, sleep longer like 8s

2023-10-15 06:31 UTC, edoardottt commented on cariddi/cariddi.tape
> +Type "echo http://testphp.vulmweb.com/ | cariddi" Sleep 500ms  Enter
here we should sleep a lil bit longer so the user can read the command typed, like 1500ms

2023-10-16 17:42 UTC, PaolaDaft commented
I've already made all the changes you requested  c;

2023-10-16 18:50 UTC, edoardottt approved these changes
lgtm

2023-10-16 18:50 UTC, merged